version: '3'
services:
  postgres:
    image: postgres:9.6.20
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: playground
    volumes:
        -  ./data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:9.6.20
    ports:
      - 5437:5432
    environment:
      POSTGRES_PASSWORD: playground
    volumes:
        -  ./data-test:/var/lib/postgresql/data