apiVersion: apps/v1
kind: Deployment
metadata:
  name: haskell-servant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haskell-servant
  template:
    metadata:
      labels:
        app: haskell-servant
    spec:
      containers:
      - name: haskell-servant
        image: elmanhasa/haskell-servant:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080

