name: Servant Play

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all --test-show-details=streaming


  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup Docker Buildx
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name multiarch --driver docker-container --use
        docker buildx inspect --bootstrap
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/armhf
        push: true
        tags: elmanhasa/haskell-servant:latest
  deploy:
   # needs: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set last commit
      run: echo "$GITHUB_SHA" > k8s/last_commit
    - uses: wixplosives/action-upload-to-s3@v10
      with:
        accessKeyId: ${{ secrets.AWS_KEY_ID }}
        secretAccessKey: ${{ secrets.AWS_ACCESS_KEY }}
        awsBucket: ${{ secrets.K8S_STATE_BUCKET }}
        sourceFolder: k8s
        s3Subfolder: ""
        tags: "from=github"
